version: '3.8'

services:
    postgres:
      image: postgres:11.8
      container_name: backend-pg
      restart: unless-stopped
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - /var/lib/postgresql/data
      ports:
        - ${DB_PORT}:5432
      networks:
        - default
    prod:
        container_name: backend-prod
        build:
            context: .
            dockerfile: ./Dockerfile
        command: bash -c "
            yarn run typeorm:run && yarn run start
          "
        depends_on:
          postgres:
            condition: service_started
        ports:
            - ${SERVER_PORT}:3000
        networks:
            - default
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    default: